CREATE TABLE configuracao (
  id BIGSERIAL PRIMARY KEY,
  chave VARCHAR(120) NOT NULL UNIQUE,
  valor VARCHAR(500) NOT NULL,
  criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
